### PR TITLE
Upgrade: Ported code to new Engine (With some caveats)

### PR DESCRIPTION
**Pull request by thearchivalone**
Another porting of a game you worked on. This one was not as straightforward as the other one and does require passing `-Wno-error=implicit-function-declarations` as a c compiler flag on Clang 17 and higher. Any place that explicitly said FreeBSD or Linux that was not for including headers, I mostly left alone due to possible breakage otherwise. The void pointers were primarily for Clang due to newer versions not liking pointer conversions of the type used.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Seems easy enough - has this been sent to upstream kmq2 by chance? If these make it there first we can just pull from latest and get the fixes that way (I'm way overdue on pulling from kmq2 anyway...)

**Comment by thearchivalone** [comment]
Not yet. Can get on that though. Just looked and they have made massive changes upstream. I saw the Github repo was out of date by a decade but the Bitbucket one seems very active.

**Comment by thearchivalone** [comment]
Pull request opened upstream: https://bitbucket.org/Knightmare66/kmquake2_stable/pull-requests/4 . Most of what was needed to get it to compile for me were not necessary there. Instead, only two lines were needed to be changed, so if this gets accepted, your game can be ran on more platforms.

**Comment by flibitijibibo** [comment]
Sounds good - if you're up for it I'd happily review a rebase on latest kmq2 though it's probably involved like you said. Worst case I'll get to it eventually, it'll just be a while!

**Comment by thearchivalone** [comment]
Ask and you shall receive. This is not 100% in line with the current upstream master. The UI code had a pretty big rewrite, so it's a mixture of old and new code based on what compiled properly along with what was changed that could break things. I commented where I ported from the old engine to the new but forgot to do it with what I back ported to get everything else to work. I also haven't tested the Linux or Windows code but everything compiles on my system now.

It also includes the mod files from upstream (can remove those if requested), but some of them were required to compile the code.

**Comment by flibitijibibo** [comment]
Oh my! Will review this ASAP, thanks for checking it out!

**Comment by thearchivalone** [comment]
Most of the backporting and mixed engine code for the UI can be found in:
1. `ui_menu.c` - This would possibly break your game menu due to how much of it was completely overhauled
2. `menu_game_saveload.c` - This was split into `menu_game_save.c` and `menu_game_load.c` files respectively; should be easy to port forward since not much was fully changed here, but breaking saves would be very problematic, so I wanted to leave this alone for the time being
3. `ui_widgets.c` - Same as ui_menu.c; the Buttons, SpinControl and Separator widgets seem to have been completely removed altogether (it's not that well-documented if they were moved or replaced)
4. Most of the multiplayer and mod ui elements were from the new engine and stubbed off using `#ifdef NOTTHIRTYFLIGHTS` due to them seeming to be more "required" for building and running than they were in the older engine version you used.

**Pull request closed without merging**
